from __future__ import annotations

from functools import lru_cache
from typing import Any

from jsonschema import Draft202012Validator, FormatChecker

from .errors import ConfigError
from .models import ZotWatchConfigV2


@lru_cache(maxsize=1)
def build_config_schema() -> dict[str, Any]:
    schema = ZotWatchConfigV2.model_json_schema(mode="validation")
    schema.update(
        {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": "ZotWatch ordinary config schema v2",
            "$comment": "Generated by the ZotWatch engine; credentials are not config fields.",
        }
    )
    Draft202012Validator.check_schema(schema)
    return schema


def validate_schema_document(data: Any) -> None:
    validator = Draft202012Validator(build_config_schema(), format_checker=FormatChecker())
    errors = sorted(
        validator.iter_errors(data),
        key=lambda error: tuple(str(part) for part in error.absolute_path),
    )
    if not errors:
        return
    error = errors[0]
    pointer = "/" + "/".join(str(part).replace("~", "~0").replace("/", "~1")
                               for part in error.absolute_path)
    detail = f"configuration does not satisfy {error.validator}"
    raise ConfigError("CONFIG_SCHEMA", detail, json_pointer=pointer)


__all__ = ["build_config_schema", "validate_schema_document"]
