name: Daily Watch & RSS

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
      ZOTERO_USER_ID: ${{ secrets.ZOTERO_USER_ID }}
      ALTMETRIC_KEY: ${{ secrets.ALTMETRIC_KEY }}
      OPENALEX_MAILTO: you@example.com
      CROSSREF_MAILTO: you@example.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m src.cli watch --rss --top 100
      - name: Prepare Pages
        run: |
          mkdir -p public
          cp -r reports/* public/ || true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - uses: actions/deploy-pages@v4
